export const THEATERS_ITEM_REQUEST = "@@THEATERITEMSREDUCER/THEATERSITEMREQUEST"
export const THEATERS_ITEM_SUCCESS = "@@THEATERSITEMREDUCER/THEATERSITEMSUCCESS"
export const THEATERS_ITEM_FAIL = "@@THEATERSITEMREDUCER/THEATERSITEMFAIL"